language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

env:
  - PHP_BIN=php
  - PHP_BIN=php-cgi

matrix:
  allow_failures:
    - php: hhvm
      env: PHP_BIN=php-cgi

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source --dev
  - vendor/bin/parallel-lint -e php,phpt --exclude vendor .

script:
  - vendor/bin/tester -p $PHP_BIN -c tests/php.ini-unix tests -s
  - vendor/bin/phpcs src --standard=vendor/zenify/coding-standard/src/ZenifyCodingStandard/ruleset.xml

after_failure:
  - 'for i in $(find ./tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done'
