language: php

php:
  - 5.5
  - 5.6
  - 7.0

install:
  - composer install --prefer-source

before_script:
  # php code sniffer
  - vendor/bin/phpcs src tests --standard=vendor/zenify/coding-standard/src/ZenifyCodingStandard/ruleset.xml --extensions=php

script:
  - phpunit --coverage-clover=coverage.clover

after_script:
  # move code coverage
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
